=== xfangming/simple-excel/src/main/resources/others/dtd/simple-excel.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT excel  (sheet)+>
        <!ATTLIST excel id CDATA #IMPLIED>
        <!ATTLIST excel code CDATA #IMPLIED>
        <!ATTLIST excel name CDATA #IMPLIED>

        <!ELEMENT sheet  (colgroup?,head?,body?)>
        <!ATTLIST sheet name CDATA #IMPLIED>

        <!ELEMENT head  (tr*)>
        <!ELEMENT body  (tr*)>


        <!ELEMENT colgroup (col*)+>
        <!ELEMENT col (#PCDATA)>
        <!ATTLIST col index CDATA #IMPLIED>
        <!ATTLIST col width CDATA #IMPLIED>

        <!ATTLIST tr height CDATA #IMPLIED
                isbold (true | false) #IMPLIED
                fontsize CDATA #IMPLIED
                fontname CDATA #IMPLIED
                color CDATA #IMPLIED
                firstrow CDATA #IMPLIED
                lastrow CDATA #IMPLIED
                firstcol CDATA #IMPLIED
                align (general | left | center | right | fill | justify | center_selection | distributed) #IMPLIED
                verticalalign (top | center | bottom | justify | distributed) #IMPLIED
                allalign (general | left | center | right | fill | justify | center_selection | distributed |
                        top | center | bottom | justify | distributed) #IMPLIED
                borderall (none | thin | medium | dashed | dotted | thick | double | hair | medium_dashed | dash_dot | medium_dash_dot | dash_dot_dot |
                        medium_dash_dot_dot | slanted_dash_dot) #IMPLIED
                bordertop (none | thin | medium | dashed | dotted | thick | double | hair | medium_dashed | dash_dot | medium_dash_dot | dash_dot_dot |
                        medium_dash_dot_dot | slanted_dash_dot) #IMPLIED
                borderright (none | thin | medium | dashed | dotted | thick | double | hair | medium_dashed | dash_dot | medium_dash_dot | dash_dot_dot |
                        medium_dash_dot_dot | slanted_dash_dot) #IMPLIED
                borderbottom (none | thin | medium | dashed | dotted | thick | double | hair | medium_dashed | dash_dot | medium_dash_dot | dash_dot_dot |
                        medium_dash_dot_dot | slanted_dash_dot) #IMPLIED
                borderleft (none | thin | medium | dashed | dotted | thick | double | hair | medium_dashed | dash_dot | medium_dash_dot | dash_dot_dot |
                        medium_dash_dot_dot | slanted_dash_dot) #IMPLIED>

        <!ELEMENT tr (th*,td*)?>

        <!ELEMENT th (#PCDATA)>
        <!ATTLIST th value CDATA #IMPLIED>
        <!ATTLIST th firstcol CDATA #IMPLIED>
        <!ATTLIST th lastcol CDATA #IMPLIED>

        <!ELEMENT td (#PCDATA)>
        <!ATTLIST td
                index CDATA #IMPLIED
                property CDATA #IMPLIED
                formula CDATA #IMPLIED
                columnsize CDATA #IMPLIED
                dateformat CDATA #IMPLIED
                value CDATA #IMPLIED
                rowspan CDATA #IMPLIED
                colspan CDATA #IMPLIED
                firstcol CDATA #IMPLIED
                lastcol CDATA #IMPLIED
                type (numeric | string | numeric | enum | date | enum) #IMPLIED

                isnullable (true | false) #IMPLIED
                maxlength CDATA #IMPLIED

=== xfangming/simple-excel/src/main/resources/simple-student2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE excel PUBLIC "excel" "https://tobiasy.oss-cn-beijing.aliyuncs.com/dtd/simple-excel.dtd">-->
<!DOCTYPE excel SYSTEM "others/dtd/simple-excel.dtd">
<excel>
    <sheet name="学生表">
        <colgroup>
            <col index="A" width='17em'/>
            <col index="B" width='17em'/>
            <col index="C" width='15em'/>
            <col index="D" width='17em'/>
            <col index="E" width='17em'/>
            <col index="F" width='17em'/>
        </colgroup>
        <head>
            <tr height="12px"  align="center" verticalalign="center" isbold = "true" fontsize="10px"><!--  color="18" -->
                <td>编号</td>
                <td>姓名</td>
                <td>年龄</td>
                <td>性别</td>
                <td>出生日期</td>
                <td>爱好</td>
                <td>价格</td>
            </tr>
        </head>
        <body>

        </body>


    </sheet>


</excel>

=== xfangming/simple-excel/src/main/resources/simple-student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE excel PUBLIC "excel" "https://tobiasy.oss-cn-beijing.aliyuncs.com/dtd/simple-excel.dtd">-->
<!--<!DOCTYPE excel SYSTEM "others/dtd/simple-excel.dtd">-->
<excel>
    <sheet name="学生表">
        <colgroup>
            <col index="A" width='17em'/>
            <col index="B" width='17em'/>
            <col index="C" width='15em'/>
            <col index="D" width='17em'/>
            <col index="E" width='17em'/>
            <col index="F" width='17em'/>
        </colgroup>
        <head>
            <tr allalign="center" height="20px" isbold="true" fontsize="12px" fontname="黑体">
                <td colspan="7">用户信息表</td>
            </tr>
            <tr align="center" height="12px" fontsize="10px" isbold="true" verticalalign="center">
                <td rowspan="2">编号</td>
                <td>姓名</td>
                <td>性别</td>
                <td>年龄</td>
                <td>生日</td>
                <td>爱好</td>
                <td rowspan="2">排名</td>
            </tr>
            <tr height="10px">
                <td>name</td>
                <td>sex</td>
                <td>age</td>
                <td>birthday</td>
                <td>favourite</td>
            </tr>
        </head>
        <body>
            <tr firstrow="10" height="10px" allalign="center" color="100"><!--  borderall="hair" -->
                <td index="0" property="code"/><!--序号 -->
                <td index="1" property="name"/><!--姓名 -->
                <td index="2" property="sex" columnsize="1" /><!--性别 -->
                <td index="3" property="age" columnsize="1" /><!--年龄 -->
                <td index="4" property="birthday" columnsize="1" dateformat="yyyy-MM-dd HH:mm:ss" /><!--出生年月 -->
                <td index="5" property="favourite" columnsize="1" /><!--爱好 -->
                <!--<td index="6" formula="SUM(A${rownum}:D${rownum})" columnsize="1" />&lt;!&ndash;函数 &ndash;&gt;-->
                <!--<td index="7" formula="IF(D${rownum}>30,'成年人',18)" columnsize="1" />&lt;!&ndash;函数 &ndash;&gt;-->
            </tr>

        </body>

    </sheet>
    <sheet>
        <colgroup>
            <col index="A" width='17em'/>
            <col index="B" width='17em'/>
            <col index="C" width='15em'/>
            <col index="D" width='17em'/>
            <col index="E" width='17em'/>
            <col index="F" width='17em'/>
        </colgroup>
        <body>
            <tr firstrow="1" height="10px" allalign="center" color="100"><!--  borderall="hair" -->
                <td index="0" property="code"/><!--序号 -->
                <td index="1" property="name"/><!--姓名 -->
                <td index="2" property="sex" columnsize="1" /><!--性别 -->
                <td index="3" property="age" columnsize="1" /><!--年龄 -->
                <td index="4" property="birthday" columnsize="1" /><!--出生年月 -->
                <td index="5" property="favourite" columnsize="1" /><!--爱好 -->
            </tr>

        </body>
    </sheet>

</excel>

=== xfangming/simple-excel/src/main/resources/simple-user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE excel PUBLIC "excel" "https://tobiasy.oss-cn-beijing.aliyuncs.com/dtd/simple-excel.dtd">
<!--<!DOCTYPE excel SYSTEM "others/dtd/simple-excel.dtd">-->
<excel>
    <sheet name="用户表">
        <colgroup>
            <col index="A" width='17em'/>
            <col index="B" width='17em'/>
            <col index="I" width='17em'/>
        </colgroup>
        <head>
            <tr allalign="center" height="20px" isbold="true" fontsize="12px" fontname="黑体" borderall="hair">
                <td colspan="9">用户信息表</td>
            </tr>
            <tr align="left" height="12px" verticalalign="center">
                <td colspan="9">描述：用户数据包含xxx，出生年月默认格式：2019-01-01</td>
            </tr>
            <tr align="center" height="15px" verticalalign="center">
                <td rowspan="7">序号</td>
                <td>姓名</td>
                <td colspan="2">性别</td>
                <td colspan="2">年龄</td>
                <td colspan="2" rowspan="3">出生年月</td>
                <td rowspan="7">爱好</td>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="6">（真实名字）</td>
                <td rowspan="6">枚举</td>
                <td rowspan="2">男</td>
                <td rowspan="3">最小值</td>
                <td rowspan="3">0</td>
            </tr>
            <tr>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="2">女</td>
                <td rowspan="4">注意事项</td>
                <td rowspan="4">格式</td>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="3">最大值</td>
                <td rowspan="3">100</td>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="2">无</td>
            </tr>
        </head>
        <body>
            <tr firstrow="9" height="10px" allalign="center" color="100">
                <td index="0" property="code"/><!--序号 -->
                <td index="1" property="name"/><!--姓名 -->
                <td index="2" property="sex" columnsize="2" /><!--性别 -->
                <td index="4" property="age" columnsize="2" /><!--年龄 -->
                <td index="6" property="birthday" columnsize="2" /><!--出生年月 -->
                <td index="8" property="favourite" columnsize="1" /><!--爱好 -->
            </tr>

        </body>
    </sheet>
    <sheet>

        <head>
            <tr allalign="center" height="20px" isbold="true" fontsize="12px" fontname="黑体" borderall="hair">
                <td colspan="9">用户信息表1</td>
            </tr>
            <tr align="left" height="12px" verticalalign="center">
                <td colspan="9">描述：用户数据包含xxx，出生年月默认格式：2019-01-01</td>
            </tr>
            <tr align="center" height="15px" verticalalign="center">
                <td rowspan="7">序号</td>
                <td>姓名</td>
                <td colspan="2">性别</td>
                <td colspan="2">年龄</td>
                <td colspan="2" rowspan="3">出生年月</td>
                <td rowspan="7">爱好</td>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="6">（真实名字）</td>
                <td rowspan="6">枚举</td>
                <td rowspan="2">男</td>
                <td rowspan="3">最小值</td>
                <td rowspan="3">0</td>
            </tr>
            <tr>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="2">女</td>
                <td rowspan="4">注意事项</td>
                <td rowspan="4">格式</td>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="3">最大值</td>
                <td rowspan="3">100</td>
            </tr>
            <tr align="center" verticalalign="center">
                <td rowspan="2">无</td>
            </tr>
        </head>
        <body>
            <tr firstrow="9" height="10px" allalign="center" color="100">
                <td index="0" property="code"/><!--序号 -->
                <td index="1" property="name"/><!--姓名 -->
                <td index="2" property="sex" columnsize="2" /><!--性别 -->
                <td index="4" property="age" columnsize="2" /><!--年龄 -->
                <td index="6" property="birthday" columnsize="2" /><!--出生年月 -->
                <td index="8" property="favourite" columnsize="1" /><!--爱好 -->
            </tr>

        </body>
    </sheet>

</excel>

=== xfangming/simple-excel/src/main/resources/formula-student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE excel PUBLIC "excel" "https://tobiasy.oss-cn-beijing.aliyuncs.com/dtd/simple-excel.dtd">-->
<!DOCTYPE excel SYSTEM "others/dtd/simple-excel.dtd">
<excel>
    <sheet name="学生表">
        <colgroup>
            <col index="A" width='17em'/>
            <col index="B" width='17em'/>
            <col index="C" width='15em'/>
            <col index="D" width='17em'/>
            <col index="E" width='17em'/>
            <col index="F" width='17em'/>
        </colgroup>
        <head>
            <tr allalign="center" height="20px" isbold="true" fontsize="12px" fontname="黑体">
                <td colspan="8">用户信息表</td>
            </tr>
            <tr align="center" height="12px" fontsize="10px" isbold="true" verticalalign="center">
                <td rowspan="2">编号</td>
                <td>姓名</td>
                <td>性别</td>
                <td>年龄</td>
                <td>生日</td>
                <td>爱好</td>
                <td rowspan="2">排名</td>
                <td rowspan="2">函数</td>
            </tr>
            <tr height="10px">
                <td>name</td>
                <td>sex</td>
                <td>age</td>
                <td>birthday</td>
                <td>favourite</td>
            </tr>
        </head>
        <body>
            <tr firstrow="3" height="10px" allalign="center" color="100"><!--  borderall="hair" -->
                <td index="0" property="code"/><!--序号 -->
                <td index="1" property="name"/><!--姓名 -->
                <td index="2" property="sex" columnsize="1" /><!--性别 -->
                <td index="3" property="age" columnsize="1" /><!--年龄 -->
                <td index="4" property="birthday" columnsize="1" format="yyyy-MM-dd HH:mm:ss" /><!--出生年月 -->
                <td index="5" property="favourite" columnsize="1" /><!--爱好 -->
                <td index="6" formula="SUM(A${rownum}:D${rownum})" columnsize="1" /><!--SUM函数 -->
                <td index="7" formula="IF(D%s>=18,D%s,'未成年人')" columnsize="1" /><!--IF函数 %s为当前行占位符 -->
                <td index="8" formula="SUM(A%s:D%s)+AVERAGE(A%s,D%s)" columnsize="2" /><!--IF函数 -->
            </tr>

        </body>

    </sheet>

</excel>
